### PR TITLE
Added the sentence offered by Dave

### LINKED ISSUE #35: Confusing future-looking statement
I had to read this a few times to wrap my head around it:

> EPUB 3.X will endeavor to remain compatible with existing content. Any EPUB 3.2 publication should be valid under any new version of EPUB published by this Working Group, unless it relies on features that are subject to errata on EPUB 3.2.

The use of "any new version" goes beyond 3.X and this charter, no? I don't think there is any errata against 3.2, but it made it sound like someone could issue errata on 3.2 in the future even though it's been replaced by a newer version.

I think the answer is as simple as switching "any new version" with "the new version", but am open to still misunderstanding the intention here.

### PR DESCRIPTION
**Pull request by iherman**
This is to fix #35 

- preview: https://raw.githack.com/w3c/epub-3-wg-charter/issue-35/index.html
- diff: https://tinyurl.com/ya4946bk

@murata2makoto @frivoal : this is a sensitive sentence in the charter, hence my request to you to have a look at it...

### CODE REVIEW

**Review by wareid — APPROVED** [review]

**Review by dauwhe — COMMENTED** [review]
I'm still wondering why we need "unless it relies of features that are subject to errata on EPUB 3.2."

**Comment by iherman** [comment]
> I'm still wondering why we need "unless it relies of features that are subject to errata on EPUB 3.2."

What would you do if there is an accepted erratum on a feature? Something that is obviously _wrong_ with it (wrong term used in a metadata, incorrect term used for a CSS feature, whatever...). Would we want to keep that due to backward compatibility, no matter what?

The probability for this to come up is probably very low. Nevertheless, we should leave this possibility open in the charter imho.

**Review by murata2makoto — CHANGES_REQUESTED** [review]
I am also worried about "unless it relies on features that are subject to errata on EPUB 3.2".  I do not think that we will lose something by dropping this phrase.

**Comment by iherman** [comment]
> I am also worried about "unless it relies on features that are subject to errata on EPUB 3.2". I do not think that we will lose something by dropping this phrase.

See my comment in https://github.com/w3c/epub-3-wg-charter/pull/36#issuecomment-622270892. We may get ourselves in a strange situation if we tie our own hands. The basis is that chairs will act responsively on something like that...

**Comment by mattgarrish** [comment]
> What would you do if there is an accepted erratum on a feature?

I think this is what is causing me confusion. What is the definition of errata?

It sounds like there doesn't have to be any significant seriousness to the issue, just that it's something reported and published in an errata document that we intend to change. Are we not allowed to fix problems that we don't publish as errata that could cause incompatibilities, even though they might be serious?

Is there some other way of phrasing it that would limit its scope, like ", unless it relies on features of EPUB 3.2 discovered to have serious issues (e.g., that have major security risks or are incorrectly identified or used)"

**Comment by iherman** [comment]
> Is there some other way of phrasing it that would limit its scope, like ", unless it relies on features of EPUB 3.2 discovered to have serious issues (e.g., that have major security risks or are incorrectly identified or used)"

I agree that this is a better formulation (no surprise:-). I may want to make it slightly less verbose

> , unless it relies on features discovered to have serious issues (e.g., related to security or an incorrect specification)

Unless somebody shouts against that I am happy to amend the text

**Comment by iherman** [comment]
The text has been updated per https://github.com/w3c/epub-3-wg-charter/pull/36#issuecomment-622418236.

I would propose to merge this on next Wednesday at the latest.

**Comment by murata2makoto** [comment]
>serious issues (e.g., related to security or an incorrect specification)

I prefer "serious issues (e.g., related to security)", since many features
are slightly incorrectly specified.

**Comment by dauwhe** [comment]
Do any existing or past charters make some claim to backward compatibility but with such a warning? I fear that this language will cause more concern about compatibility, without changing what the Working Group is able to do.

**Comment by iherman** [comment]
> Do any existing or past charters make some claim to backward compatibility but with such a warning? I fear that this language will cause more concern about compatibility, without changing what the Working Group is able to do. (@dauwhe)

All comparisons are risky, but we had something similar in the [JSON-LD 1.1 WG charter](https://www.w3.org/2018/03/jsonld-wg-charter.html), which said:

> All changes must preserve backward compatibility for JSON-LD 1.0 documents. This means that, when processing existing JSON-LD documents, JSON-LD 1.1 processors generate the same expanded output, unless that output is subject to [errata in JSON-LD 1.0](https://www.w3.org/2001/sw/wiki/JSON_LD_Errata) or is otherwise an unspecified implementation detail.

The difference is that JSON-LD 1.1 was based on a previous recommendation (1.0) which had a formal errata mechanism.

The WG is now (almost) in PR phase and the backward compatibility clause did create some problems in solving issues. But, by and large, things were fine.

**Comment by iherman** [comment]
> > serious issues (e.g., related to security or an incorrect specification)
> 
> I prefer "serious issues (e.g., related to security)", since many features
> are slightly incorrectly specified.

"slightly incorrectly specified" is not the same as having an incorrect specification; the assessment should remain in the group's hand. But it is always good to have several examples in something like that, to make it sure that we are not governed by one issue only. But we are getting into minute wordsmithing...

**Comment by murata2makoto** [comment]
@iherman 

First, I do not think that this is "minute wordsmithing".  If people see non-negligible risks and negligible advantages, formal objection may well be raised.

One possible interpretation of "unless it relies on features of EPUB 3.2 discovered to have serious issues (e.g., related to security or an incorrect specification)" is:

- You can propose to drop any feature of 3.2 from the next version of EPUB.
- But you are obliged to propose errata to 3.2 at the same time.
-  If you think that something is not correctly specified, you have a good reason.

If somebody does so (just like people did so during the development of 3.1), your text does not immediately stop that discussion.  I do not want to be in an awkward corner again.

I would like to drop this "unless" clause, but I can live with "unless it relies on features of EPUB 3.2 discovered to have serious issues (e.g., fatal security problems)".  Even if a feature is hopelessly underspecified and completely non-interoperable (e.g., most of the SSV values), I strongly think that it should be kept.

**Comment by iherman** [comment]
> @murata2makoto 
> 
> First, I do not think that this is "minute wordsmithing". If people see non-negligible risks and negligible advantages, formal objection may well be raised.

And that is perfectly fine. The W3C process assures that at _any point_ a member of the WG can make clear that a feature discussion may lead to a formal objection, and it is up to the chairs to seek consensus to avoid that. This is just normal working group operation as defined and assured by the process.

> 
> One possible interpretation of "unless it relies on features of EPUB 3.2 discovered to have serious issues (e.g., related to security or an incorrect specification)" is:
> 
> * You can propose to drop any feature of 3.2 from the next version of EPUB.
> * But you are obliged to propose errata to 3.2 at the same time.
> * If you think that something is not correctly specified, you have a good reason.

I do not see any problems with these rules per se: the working group, led by the chairs, can decide that this is the way the WG would operate (or not, and we have to have another procedure then). At this moment, the only thing we are doing is to define the charter, and to give the chairs and the WG enough room to set up its procedures when the time comes. It is not up to the charter to define, in minute details, the way the WG would operate.

Anyway. We are discussing on a parenthetical part in the sentence belonging to an 'e.g.' clause; if the only item there is referring to security issues only, I can live with that. One of the first thing the WG will have to do is to set up its own operating rules, like the one you outlined above, but that is not the level of details for the charter in my view.

**Comment by mattgarrish** [comment]
I'm not terribly worried that anything in 3.2 relies on an incorrect specification, so we're probably arguing over nothing. I think the only time that applied is when we added aria-describedat only to have it subsequently die before becoming a recommendation.

But, in the interests of closing this, could we swap out "incorrect specification" with

>, unless it relies on features discovered to have serious issues (e.g., related to security or an invalid implementation).

Would that reduce any confusion with the regular clarifications we do? Features like epub:type, switching, etc. are validly implemented per html extension rules, whether you like them or not, so it wouldn't be an argument for removing them.

**Comment by dauwhe** [comment]
Note that we say "should" rather than "must." Is that enough wiggle room for errata? 

I'm tempted to make this paragraph much simpler:

> The primary goal of EPUB 3.X is to remain compatible with existing content. Any existing valid EPUB 3.2 should remain valid under EPUB 3.X. 

I'm also starting to think that talking about an XML attribute value in the scope section of a charter is too much detail :)

**Comment by iherman** [comment]
> Note that we say "should" rather than "must." Is that enough wiggle room for errata?
> 

This is a 'should' rather than a _SHOULD_... Ie, we fall back to a common English usage not spec talk. Maybe it does give wiggle room, but maybe others will interpret it differently...

> I'm tempted to make this paragraph much simpler:
> 
> > The primary goal of EPUB 3.X is to remain compatible with existing content. Any existing valid EPUB 3.2 should remain valid under EPUB 3.X.

I could just repeat https://github.com/w3c/epub-3-wg-charter/pull/36#issuecomment-622270892, ie, that it may bite us later if we tie our hands.

I think the explicit wiggle room is important to avoid real problems later on. I am fine keeping only the security example in the parenthetical part of the sentence, but I would feel uncomfortable if there was no room at all.

As I said in https://github.com/w3c/epub-3-wg-charter/pull/36#issuecomment-623349727 one of the first actions of the WG will be to establish a more detailed WG policy on the matter.

> 
> I'm also starting to think that talking about an XML attribute value in the scope section of a charter is too much detail :)

You mean the reference to `epub:type` or `ssml:*`? The reason I would think it is important is not for the publishing community but for other W3C members looking at the charter. Many would think that moving from XHTML to HTML is a no-brainer and would not realize that, for some situations, it may not work. These are maybe the most obvious issues. This reference may make the possible charter discussions easier...

**Comment by mattgarrish** [comment]
> You mean the reference to `epub:type` or `ssml:*`?

I believe it's a reference to dropping the following sentence:

> In particular, all EPUB 3 specifications defined by this Working Group will use version=”3.0” for the package file, to ensure compatibility with previous versions of EPUB 3.

I agree actually referencing the attribute is a bit on the technical side, and looking at it again it's a bit tangential to the content validity question -- we could strip EPUB bare of all its features and not change the version number if we wanted. The problem changing the version number presents is the possibility existing reading systems won't open files with a higher number.

Couldn't this be moved to the out-of-scope section, though, since that's more its focus?

> - Changes to the package document version number. The number will remain "3.0" to ensure reading systems do not reject EPUB 3 files.

**Comment by iherman** [comment]
Ah! That is what you meant...

I believe this sentence landed in the scope section because, afaik, it was one of the central issues back in the days when the EPUB 3.2 work started.

Personally, I do not really care whether it is in the out-of-scope or the scope section. I am just uneasy moving things around in the charter at this point; it all looks like complicated construction and if we move things around it might lead to reopening discussions. I would prefer to leave it as is for that very pragmatic reason...

**Comment by dauwhe** [comment]
I tried to make some changes to this, and it ended up as a new PR because I am git-challenged. See #37. Sorry :)

**Comment by dauwhe** [comment]
Ah, it looked like that worked! #37 has merged into this branch.

**Review by dauwhe — APPROVED** [review]

**Review by dauwhe — APPROVED** [review]
Thanks Ivan!!!

**Review by wareid — APPROVED** [review]

**Pull request merged**
