### PR TITLE
Added the wording proposed by @mattgarrish in issue #23

### LINKED ISSUE #23: Keeping backward compatibility and maintenance of EPUB business ecosystem; without any disruptions to be caused by the EPUB Recommendation Track process
In reference to the proposed charter above and intentions to moving forward with EPUB 3 for W3C Recommendation Track (“Rec Track”), we are writing this on behalf of the Japanese publishing industry community including publishers, eBook distributors, eBook reading system developers/providers, industry organizations, et al currently participating to the EPUB 3 based eBook business ecosystem to secure and confirm that the EPUB Working Group Charter is in compliance with the following:

Backward compatibility of the EPUB 3 specifications shall be maintained thoroughly.
The Rec Track process will not ill-effect the EPUB 3 specifications pertaining to the current EPUB business ecosystem from file creations, distribution and reading system.
The above basis shall be maintained even if the rec track process may seek the cases of utilizing a feature that was never implemented anywhere and adding any new features.In the event any doubt of occurrence of causing issues with the above basis, EPUB Work Group once established shall report details of such causes to all the members of Publishing@ W3C and seek consensus to proceed.

Further, we are in agreement with the Mr. Florian Rivoal’s already uploaded messages below to the EPUP Working Group proposed Charter and by quoting them, we intend to seek confirmation of the proposed Charter to conform with the quoted messages.

Junichi Yoshii (Kodansha)
Daihei Shiohama (Media Do)

(Mr. Florian Rivoal’s GitHub messages)
This doesn't mean we cannot change anything, but if the risk part of the risk/benefit trade-of is more pronounced, the benefit bar to met for a change or an addition to be worth doing is also higher. In order to judge that, knowing what the change is (which the WG will likely be good at) is insufficient, and knowing why the change or set of changes is being proposed is important as well.

By and large, the publishing industry, which is the target of the EPUB family of specifications, operates on thinner margins and smaller budgets than the pure-software core of the Web industry. Also, a smaller percentage of its workforce is composed of technical/software people. In order to help make the case of why companies should put time and resources into participating, stating the motivations upfront is important.

As an exception, features present in EPUB 3.2 must be kept when advancing to Proposed Recommendation even if there is no known implementation in a reading system, as long as documents using of these feature were accepted by epubcheck. Such features should (must?) be marked as deprecated (according to this definition), and related requirements on Reading Systems may be simplified, but documents using these features must not be made non-conformant to newer versions of the EPUB specification.

### PR DESCRIPTION
**Pull request by iherman**
This may be a consensus solution to #23 and #8 

@murata2makoto @frivoal can that be accepted as answer to the issues (and close #23 and #8)?

Preview: https://raw.githack.com/w3c/epub-3-wg-charter/feature-deprecation/index.html (the only difference is in the 'out of scope' section, first bullet item.

### CODE REVIEW

**Comment by iherman** [comment]
- Preview: https://raw.githack.com/w3c/epub-3-wg-charter/feature-deprecation/index.html
- Diff: https://tinyurl.com/yaq44ve4

**Review by dauwhe — APPROVED** [review]

**Comment by iherman** [comment]
@wareid @TzviyaSiegman are you o.k. with this change?

@murata2makoto @frivoal does this answer to your concerns (compounded with other recent [changes on success criteria](https://w3c.github.io/epub-3-wg-charter/#success-criteria))?

**Review by wareid — APPROVED** [review]

**Review by TzviyaSiegman — APPROVED** [review]

**Comment by frivoal** [comment]
I support this change, and it does address the part of issue #8 I wrote about success criteria. Issue #8 did include other concerns, and I'd like to think again whether the various changes made in the document are sufficient to address them, so I'm not closing it just yet, but I do feel we're on the right track.

**Comment by iherman** [comment]
Thanks @frivoal. I will merge this PR to create a clearer situation, and I will leave #8 (and, as a consequence, #23) open for now.

**Pull request merged**
